version: 2
jobs:
  build:
    docker:
      - image: docker:19.03.13-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: build docker image
          command: |
            docker pull praqma/helmsman:latest
            docker build --cache-from=praqma/helmsman:latest -t helmsman .

  release:
    docker:
      - image: goreleaser/goreleaser
        entrypoint: /bin/bash
    working_directory: "/go/src/github.com/Praqma/helmsman"
    steps:
      - run:
          name: install git
          command: apk update && apk add --no-cache git openssh
      - checkout
      - run:
          name: release
          command: |
            goreleaser release --release-notes release-notes.md

  docker-release:
    working_directory: "/tmp/go/src/helmsman"
    machine: true
    steps:
      - checkout
      - run:
          name: build docker images and push them to dockerhub
          command: |
            helm_versions=( "v3.3.4" "v3.4.2" "v3.5.4" )

            TAG=$(git describe --abbrev=0 --tags)
            docker login -u $DOCKER_USER -p $DOCKER_PASS

            for HELM_VERSION in "${helm_versions[@]}"
            do
              docker build -t praqma/helmsman:$TAG-helm-$HELM_VERSION --build-arg GLOBAL_HELM_VERSION=$HELM_VERSION . --no-cache
              docker push praqma/helmsman:$TAG-helm-$HELM_VERSION
            done

workflows:
  version: 2
  build-test-push-release:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
      - docker-release:
          requires:
            - release
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
