# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    working_directory: "/go/src/helmsman"
    docker:
      - image: praqma/helmsman-test
    steps:
      - checkout
      - run:
          name: Build helmsman
          command: |
            echo "building ..."
            export GOOS=linux
            make build

  test:
    working_directory: "/go/src/helmsman"
    docker:
      - image: praqma/helmsman-test
    steps:
      - checkout
      - run:
          name: Unit test helmsman
          command: |
            echo "running tests ..."
            export GOOS=linux
            make test
  release:
    working_directory: "/tmp/go/src/helmsman"
    machine: true
    steps:
      - checkout
      - run:
          name: Release helmsman
          command: |
            echo "releasing ..."
            make release

      - run:
          name: build docker images and push them to dockerhub
          command: |
            TAG=$(git describe --abbrev=0 --tags)
            docker login -u $DOCKER_USER -p $DOCKERHUB
            docker build -t praqma/helmsman:$TAG-helm-v2.14.3 --build-arg HELM_VERSION=v2.14.3 --build-arg HELM_DIFF_VERSION=master dockerfile/. --no-cache
            docker push praqma/helmsman:$TAG-helm-v2.14.3
            docker build -t praqma/helmsman:$TAG-helm-v2.13.1 --build-arg HELM_VERSION=v2.13.1 --build-arg HELM_DIFF_VERSION=master dockerfile/. --no-cache
            docker push praqma/helmsman:$TAG-helm-v2.13.1
            docker build -t praqma/helmsman:$TAG-helm-v2.12.3 --build-arg HELM_VERSION=v2.12.3 --build-arg HELM_DIFF_VERSION=master dockerfile/. --no-cache
            docker push praqma/helmsman:$TAG-helm-v2.12.3
            docker build -t praqma/helmsman:$TAG-helm-v2.11.0 --build-arg HELM_VERSION=v2.11.0 --build-arg HELM_DIFF_VERSION=v2.11.0+5 dockerfile/. --no-cache
            docker push praqma/helmsman:$TAG-helm-v2.11.0
            docker build -t praqma/helmsman:$TAG-helm-v2.10.0 --build-arg HELM_VERSION=v2.10.0 --build-arg HELM_DIFF_VERSION=v2.10.0+1 dockerfile/. --no-cache
            docker push praqma/helmsman:$TAG-helm-v2.10.0


workflows:
  version: 2
  build-test-push-release:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - test:
          requires:
            - build
          filters:
            tags:
              only: /.*/  
      - release:
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
