## This is a minimal example.
## It will use your current kube context and will deploy Tiller without RBAC service account.
## For the full config spec and options, check https://github.com/Praqma/helmsman/blob/master/docs/desired_state_specification.md

[helmRepos]
  jenkins = "https://charts.jenkins.io"
  jfrog = "https://charts.jfrog.io"

[namespaces]
  [namespaces.staging]

[apps]
  [apps.jenkins]
    namespace = "staging"
    enabled = true
    chart = "jenkins/jenkins"
    version = "2.15.1"

  [apps.artifactory]
    namespace = "staging"
    enabled = true
    chart = "jfrog/artifactory"
    version = "11.4.2"
